<!--
    使用 xacro 实现自己的一个USV：

    实现思路:
    1.将一些常量、变量封装为 xacro:property
      比如:PI 值、USV船体尺寸、桨叶半径、桨叶宽度 ....
    2.使用 宏 封装桨叶，调用相关宏生成驱动轮与支撑轮
    3.用三个部分组成USV，一个box作为船体，两个圆柱体作为桨叶（可以实现360度旋转）

-->


<!-- 根标签，必须声明 xmlns:xacro -->
<robot name="myusv" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- 属性封装 -->
    <xacro:property name="paddle_radius" value="0.0325" />
    <xacro:property name="paddle_width" value="0.0015" />
    <xacro:property name="PI" value="3.1415927" />
    <xacro:property name="base_link_length" value="0.08" />
    <xacro:property name="lidi_space" value="0.015" />

    <!-- 宏 -->
    <xacro:macro name="paddle_func" params="paddle_name flag" >
        <link name="${paddle_name}_paddle">
            <visual>
                <geometry>
                    <cylinder radius="${paddle_radius}" length="${paddle_length}" />
                </geometry>

                <origin xyz="0 0 0" rpy="${PI / 2} 0 0" />

                <material name="color">
                    <color rgba="0 0 0 0.3" />
                </material>
            </visual>
        </link>

        <!-- 3-2.joint -->
        <joint name="${paddle_name}2link" type="continuous">
            <parent link="base_link"  />
            <child link="${paddle_name}_paddle" />
            <!-- 
                x 无偏移
                y 车体半径
                z z= 车体高度 / 2 + 离地间距 - 车轮半径

            -->
            <origin xyz="0 ${0.1 * flag} ${(base_link_width / 2 -  paddle_radius) * -1}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>

    </xacro:macro>


   <xacro:macro name="base_func">
           <link name="base_link">
            <visual>
                <geometry>
                    <box radius="${paddle_radius}" length="${paddle_length}" />
                </geometry>

                <origin xyz="0 0 0" rpy="0 0 0" />

                <material name="color">
                    <color rgba="0 0 0 0.3" />
                </material>
            </visual>
        </link>
    </xacro:macro>

    <xacro:base_func/>
    <xacro:paddle_func paddle_name="left" flag="1" />
    <xacro:paddle_func paddle_name="right" flag="-1" />
</robot>
